### ISSUE TITLE
Not running

### ISSUE THREAD

**Issue by samuelfarrus** [danielptv/tap-db2#298]
Successfully installed `tap-db2 --variant danielptv`, but `meltano run` returns the following error:

`Run invocation could not be completed as block failed: Cannot start plugin tap-db2: 'utf-8' codec can't decode byte 0xe3 in position 54: invalid continuation byte`

Also, `meltano config tap-db2 test` returns:

```
Plugin configuration is invalid
'utf-8' codec can't decode byte 0xe3 in position 54: invalid continuation byte
```

My setup: Windows 11, meltano 3.7.4, python 3.13

**Comment by danielptv** [comment]
Hi,

I've tried to reproduce the error you are getting but was not able to.

I had never tested Meltano in Windows before so I've set up a fresh test project. One important difference is that I have used Python3.12 rather than 3.12 since I already had it installed.

Could you please test with Python3.12 also, just to be sure? Additionally, please provide your `meltano.yml` so I can try to reproduce further. Parts relevant to tap-db2 are enough.

**Comment by samuelfarrus** [comment]
Greetings @danielptv ! Thank you in advance for the assistance.

Tried on Python 3.12.3 and it worked.

My meltano.yaml file:

```yaml
# ...
plugins:
  extractors:
  - name: tap-db2
    variant: danielptv
    pip_url: git+https://github.com/danielptv/tap-db2.git
    config:
      host: <db_host>
      port: 57000
      database: <db_name>
      user: <db_user>
# ...
```
